language: node_js
node_js:
  - "0.12"
env:
  global:
    - secure: RhmfgnPkrCcjOTWkfYFZS5zlBQhte2cAAtjA/bIKH4qhaLsWHHS0ApJ065PJs4H/lfslWSfnRcUpaeFq8hhr/9dMlCxFJc5CTJ2EfmV56NjsiaETtrxHdNVFtZU/DxJnSxnW4revbFkk/mM6JZ+P7XwVv+iitKhx3uRpX2/rKWA=
    - secure: hmu/VH1viA8oPFjxBrjvnLrNa0PnfXsIKMMv9ZmgpXthdhTtuReD9rPmbnFzNh9MyCkLSZcndJakpDu9SwHVDcs5eyV72fuXHW/0htyN9eNTMyShrNIpOJe6JUqMez7MxQU9J45IJGSvbyEfrbZ20mbGGzJ41KnEZ0IfwODPcMY=
    - secure: JrGUKctdLs9cwJlLtAHahYlJmE0jGt4/Rkt6RMD20btQcBhcvAmTJFICsYaac4h5cc0krStkeskXkZ8YANhB3OGzbLw7PGcTjnFUvVwpZKRmnsUV6puwEUH0AC6XNl4J2r9G8wPOZyy4WVxZlbdFi9To8dc8X2iufo2RyWf3MDK+OHm0CuMj6JXnJzA5FMk3pxZOjopG2W0/uAZETd9FPWmm8J6NZRsvx4nsQz2/eBjH2+MaoQYK4AcqvFFjwuume2Oali8+NQLyu7zpbfaLtLBg9+53hc59KFB/ha8Q6o0APz6rtTtgwRDckFHUVaxduTaWyKXvD0Krj3d1BvDnZVRebx4OYLstHUfnY4B6CCgKJ0ZdLVIf+I6UtHKoDu+qNc0e7EYY9rRDwFAJiE1OU+QhVE+m5UbUxHY0pCvbiKSsKe7vpe0dDvrsnuZTw8N53n7ZQF3QbMhxwLD+GONWWK6RLK1gbVbvcrBCtBsFPr6rWyYMQPPM09+aKmRTW2uRGAuf8tudiKf19Znd4EMKjVnGAW5qDxEJ2o9x357BXLCjeNH/BjxLOW4oH3bqukMXE4EmLpb6eUXCKVaRUD4+adqw8E3/iKaowotwwPl39dnqk5AmiXY4ID6vaTtFlyg1axDUfZwFysObIP1T+SDMDu2Nx3VQMlRKC4AOOmDz5co=
    - secure: Qul/FmeTIuC6origZyNVniL8xm7ah29V0DJVvx7OP2+ibOtORuTa9od7gyZyhc3cuCegAaL8Q+kAxiNedy7m/UdE5eDvgSBpVJsO7g1DxSlb9dB082BSY+7VSjYY9Q08koJgTZZ/pnV3MSL9TaQzxn+HTH/nIiHgn+ZaQ0l19kjzeGclkN7HgPwpjNhb6OAtwTjf82Ys10nunv0pATgmc4BkqXP/UnJ0DXF8+tO+AVz2IRYstk0j5u75UOONvp7OTt4cpZqBK3iDY2zljduXnJ4NbOwdwi8dBk2tOLQCq+il28kM/adsyUomcj8h3qAN4RQD95yE37XZQrx1bT+aJLtphQKsaYmDFVdj5OWOOAjTyZ3J7FROyRmI74tPAAfEXBxueuP15Jlogyci3Bp341cgtBu7EX9etd2W1uTSVWDiUfFedIXgE8py5PFSX48SC0ay6hkeMei7wQ5R4d7tpuQpJ1f/zXR4YsdgKcTHU7XM13nP8QrSAa76QhRtubW0KPoIncftzvw/UKjc5pofqd8+ylQ66Xhig92jabyLKY+1CmfSRaBgj0IqLmCB08SOW7NnvPVAYqqnYNHpdCQMMrqKzMgJepBAruD/PnFAQ6/0Z6Gbkh8AUqkghMXUkf2oxz9uHyIAGf4Lo0T+BBaZWNsh9fitHdCO3YLCiVnet+Y=
before_install:
  - npm install -g bower
  - npm install -g grunt-cli
install:
  - npm install
script:
  - grunt test:development
  - grunt test
  - grunt e2e --ci
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < coverage/lcov.info
addons:
  sauce_connect: true
